forum_modules/exporter/urls.py
from django.conf.urls import patterns, url, include
from django.utils.translation import ugettext as _

from views import state, running, download

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('state/')),  state, name='exporter_state'),
    url(r'^%s(?P<mode>\w+)/%s$' % (_('admin/'), _('running/')),  running, name='exporter_running'),
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('download/')),  download, name='exporter_download'),
)

forum_modules/robotstxt/urls.py
from django.conf.urls import patterns, url, include
from django.http import  HttpResponse
import settings

urlpatterns = patterns('',
    (r'^robots.txt$',  lambda r: HttpResponse(settings.ROBOTS_FILE.value, content_type='text/plain')),
)

forum_modules/stats/urls.py
from django.conf.urls import patterns, url, include
from django.utils.translation import ugettext as _

from views import stats_index, stats_check

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('stats/'), _('check/')),  stats_check, name='stats_check'),
)

urls.py
from django.conf.urls import patterns, url, include
from django.utils.translation import ugettext as _
from django.conf import settings

urlpatterns = patterns('',
    (r'', include('forum.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns = patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    ) + urlpatterns

handler404 = 'forum.views.meta.page'
handler500 = 'forum.views.meta.error_handler'

forum/models/case.py
from base import *
from tag import Tag
from django.utils.translation import ugettext as _

class CaseManager(NodeManager):
    def search(self, keywords, **kwargs):
        return False, self.filter(models.Q(title__icontains=keywords) | models.Q(body__icontains=keywords))

class Case(Node):
    class Meta(Node.Meta):
        proxy = True


    favorite_count = DenormalizedField("actions", action_type="favorite", canceled=False)

    friendly_name = _("case")
    objects = CaseManager()

    @property    
    def view_count(self):
        return self.extra_count

    @property
    def headline(self):
        return self._headline()

    def _headline(self):
        if self.nis.deleted:
            return _('[deleted] ') + self.title

        if self.nis.closed:
            return _('[closed] ') + self.title

        return self.title

    @models.permalink    
    def get_absolute_url(self):
        return ('case', (), {'id': self.id, 'slug': django_urlquote(slugify(self.title))})
        
    def meta_description(self):
        return self.summary

    def get_revision_url(self):
        return reverse('case_revisions', args=[self.id])

    def get_related_questions(self, count=10):
        cache_key = '%s.related_questions:%d:%d' % (settings.APP_URL, count, self.id)
        related_list = cache.get(cache_key)

        if related_list is None:
            related_list = Node.objects.filter_state(deleted=False).values('id').filter(tags__id__in=[t.id for t in self.tags.all()]
            ).exclude(id=self.id).annotate(frequency=models.Count('id')).order_by('-frequency')[:count]
            cache.set(cache_key, related_list, 60 * 60)

        return [Node.objects.get(id=r['id']) for r in related_list]


class CaseRevision(NodeRevision):
    class Meta:
        proxy = True
        

forum/models/meta.py
from django.utils.translation import ugettext as _
from base import *

class Vote(models.Model):
    user = models.ForeignKey(User, related_name="votes")
    node = models.ForeignKey(Node, related_name="votes")
    value = models.SmallIntegerField()
    action = models.OneToOneField(Action, related_name="vote")
    voted_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')


class Flag(models.Model):
    user = models.ForeignKey(User, related_name="flags")
    node = models.ForeignKey(Node, related_name="flags")
    reason = models.CharField(max_length=300)
    action = models.OneToOneField(Action, related_name="flag")
    flagged_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')


class Badge(BaseModel):
    GOLD = 1
    SILVER = 2
    BRONZE = 3

    type        = models.SmallIntegerField()
    cls         = models.CharField(max_length=50, null=True)
    awarded_count = models.PositiveIntegerField(default=0)
    
    awarded_to    = models.ManyToManyField(User, through='Award', related_name='badges')

    def get_handler(self):
        from forum.badges import BadgesMeta
        return BadgesMeta.by_id.get(self.id, None)

    @property
    def name(self):
        cls = self.get_handler()
        return cls and cls.name or _("Unknown")

    @property
    def description(self):
        cls = self.get_handler()
        return cls and cls.description or _("No description available")

    @models.permalink
    def get_absolute_url(self):
        return ('badge', [], {'id': self.id, 'slug': slugify(self.name)})

    def save(self, *args, **kwargs):
        if isinstance(self.awarded_count, models.expressions.ExpressionNode):
            super(Badge, self).save(*args, **kwargs)
            self.awarded_count = self.__class__.objects.filter(id=self.id).values_list('awarded_count', flat=True)[0]
        else:
            super(Badge, self).save(*args, **kwargs)


    class Meta:
        app_label = 'forum'


class Award(models.Model):
    user = models.ForeignKey(User)
    badge = models.ForeignKey('Badge', related_name="awards")
    node = models.ForeignKey(Node, null=True)

    awarded_at = models.DateTimeField(default=datetime.datetime.now)

    trigger = models.ForeignKey(Action, related_name="awards", null=True)
    action = models.OneToOneField(Action, related_name="award")


    class Meta:
        unique_together = ('user', 'badge', 'node')
        app_label = 'forum'

forum/models/question.py
from base import *
from tag import Tag
from django.utils.translation import ugettext as _

class QuestionManager(NodeManager):
    def search(self, keywords, **kwargs):
        return False, self.filter(models.Q(title__icontains=keywords) | models.Q(body__icontains=keywords))

class Question(Node):
    class Meta(Node.Meta):
        proxy = True

    answer_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer")
    accepted_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer", marked=True)
    favorite_count = DenormalizedField("actions", action_type="favorite", canceled=False)

    friendly_name = _("question")
    objects = QuestionManager()

    @property
    def closed(self):
        return self.nis.closed

    @property    
    def view_count(self):
        return self.extra_count

    @property
    def headline(self):
        return self._headline()

    def _headline(self):
        if self.nis.deleted:
            return _('[deleted] ') + self.title

        if self.nis.closed:
            return _('[closed] ') + self.title

        return self.title

    @property
    def accepted_answers(self):
        return self.answers.filter(~models.Q(state_string__contains="(deleted)"), marked=True)

    @models.permalink    
    def get_absolute_url(self):
        return ('question', (), {'id': self.id, 'slug': django_urlquote(slugify(self.title))})
        
    def meta_description(self):
        return self.summary

    def get_revision_url(self):
        return reverse('question_revisions', args=[self.id])

    def get_related_questions(self, count=10):
        cache_key = '%s.related_questions:%d:%d' % (settings.APP_URL, count, self.id)
        related_list = cache.get(cache_key)

        if related_list is None:
            related_list = Question.objects.filter_state(deleted=False).values('id').filter(tags__id__in=[t.id for t in self.tags.all()]
            ).exclude(id=self.id).annotate(frequency=models.Count('id')).order_by('-frequency')[:count]
            cache.set(cache_key, related_list, 60 * 60)

        return [Question.objects.get(id=r['id']) for r in related_list]
    



class QuestionSubscription(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Node)
    auto_subscription = models.BooleanField(default=True)
    last_view = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        app_label = 'forum'


class QuestionRevision(NodeRevision):
    class Meta:
        proxy = True
        

forum/models/tag.py
import datetime
from base import *

from django.conf import settings as django_settings
from django.core.cache.backends.base import BaseCache
from django.utils.translation import ugettext as _
from django.utils.encoding import smart_unicode, force_unicode

from forum import modules

class ActiveTagManager(CachedManager):
    use_for_related_fields = True

    def get_queryset(self):
        return super(ActiveTagManager, self).get_queryset().exclude(used_count__lt=1)

class Tag(BaseModel):
    name            = models.CharField(max_length=255, unique=True)
    created_by      = models.ForeignKey(User, related_name='created_tags')
    created_at      = models.DateTimeField(default=datetime.datetime.now, blank=True, null=True)
    marked_by       = models.ManyToManyField(User, related_name="marked_tags", through="MarkedTag")
    # Denormalised data
    used_count = models.PositiveIntegerField(default=0)

    active = ActiveTagManager()

    class Meta:
        ordering = ('-used_count', 'name')
        app_label = 'forum'

    def __unicode__(self):
        return force_unicode(self.name)

    def add_to_usage_count(self, value):
        if self.used_count + value < 0:
            self.used_count = 0
        else:
            self.used_count = models.F('used_count') + value

    def cache_key(self):
        return self._generate_cache_key(Tag.safe_cache_name(self.name))

    @classmethod
    def safe_cache_name(cls, name):
        return "".join([str(ord(c)) for c in name])

    @classmethod
    def infer_cache_key(cls, querydict):
        if 'name' in querydict:
            cache_key = cls._generate_cache_key(cls.safe_cache_name(querydict['name']))

            if len(cache_key) > django_settings.CACHE_MAX_KEY_LENGTH:
                cache_key = cache_key[:django_settings.CACHE_MAX_KEY_LENGTH]

            return cache_key

        return None

    @classmethod
    def value_to_list_on_cache_query(cls):
        return 'name'

    @models.permalink
    def get_absolute_url(self):
        return ('tag_questions', (), {'tag': self.name})

class MarkedTag(models.Model):
    TAG_MARK_REASONS = (('good', _('interesting')), ('bad', _('ignored')))
    tag = models.ForeignKey(Tag, related_name='user_selections')
    user = models.ForeignKey(User, related_name='tag_selections')
    reason = models.CharField(max_length=16, choices=TAG_MARK_REASONS)

    class Meta:
        app_label = 'forum'

forum/models/term.py
from base import *
from tag import Tag
from django.utils.translation import ugettext as _

class TermManager(NodeManager):
    def search(self, keywords, **kwargs):
        return False, self.filter(models.Q(title__icontains=keywords) | models.Q(body__icontains=keywords))

class Term(Node):
    class Meta(Node.Meta):
        proxy = True

    friendly_name = _("term")
    objects = TermManager()

    @property
    def headline(self):
        return self._headline()

    def _headline(self):
        return self.title


    @models.permalink    
    def get_absolute_url(self):
        return ('term', (), {'id': self.id, 'slug': django_urlquote(slugify(self.title))})
        
    def meta_description(self):
        return self.summary

    def get_revision_url(self):
        return reverse('term_revisions', args=[self.id])

    def get_related(self, count=10):
        cache_key = '%s.related_terms:%d:%d' % (settings.APP_URL, count, self.id)
        related_list = cache.get(cache_key)

        if related_list is None:
            related_list = Term.objects.filter_state(deleted=False).values('id').filter(tags__id__in=[t.id for t in self.tags.all()]
            ).exclude(id=self.id).annotate(frequency=models.Count('id')).order_by('-frequency')[:count]
            cache.set(cache_key, related_list, 60 * 60)

        return [Term.objects.get(id=r['id']) for r in related_list]
    

forum/forms/admin.py
import socket
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.admin.widgets import FilteredSelectMultiple, AdminDateWidget
from qanda import TitleField, EditorField
from forum import settings
from forum.models.node import NodeMetaClass
from forum.models import User

class IPListField(forms.CharField):
    def clean(self, value):
        ips = [ip.strip() for ip in value.strip().strip(',').split(',')]
        iplist = []

        if len(ips) < 1:
            raise forms.ValidationError(_('Please input at least one ip address'))

        for ip in ips:
            try:
                socket.inet_aton(ip)
            except socket.error:
                raise forms.ValidationError(_('Invalid ip address: %s' % ip))

            if not len(ip.split('.')) == 4:
                raise forms.ValidationError(_('Please use the dotted quad notation for the ip addresses'))

            iplist.append(ip)

        return iplist

class MaintenanceModeForm(forms.Form):
    ips = IPListField(label=_('Allow ips'),
                      help_text=_('Comma separated list of ips allowed to access the site while in maintenance'),
                      required=True,
                      widget=forms.TextInput(attrs={'class': 'longstring'}))

    message = forms.CharField(label=_('Message'),
                              help_text=_('A message to display to your site visitors while in maintainance mode'),
                              widget=forms.Textarea)


TEMPLATE_CHOICES = (
('default', _('Default')),
('sidebar', _('Default with sidebar')),
('none', _('None')),
)

RENDER_CHOICES = (
('markdown', _('Markdown')),
('html', _('HTML')),
('escape', _('Escaped'))
)

class UrlFieldWidget(forms.TextInput):
    def render(self, name, value, attrs=None):
        if not value:
            value = ''

        return """
                <input class="url_field" type="text" name="%(name)s" value="%(value)s" />
                <a class="url_field_anchor" target="_blank" href="%(app_url)s"></a>
            """  % {'name': name, 'value': value, 'app_url': settings.APP_URL}


class PageForm(forms.Form):
    def __init__(self, page, *args, **kwargs):
        if page:
            initial = page.extra
            initial.update(dict(title=page.title, content=page.body))
            super(PageForm, self).__init__(initial=initial, *args, **kwargs)
        else:
            super(PageForm, self).__init__(*args, **kwargs)


    title  = forms.CharField(label=_('Title'), max_length=255, widget=forms.TextInput(attrs={'class': 'longstring'}),
                             initial='New page')
    path  = forms.CharField(label=_('Page URL'), widget=UrlFieldWidget, initial='pages/new/')

    content = forms.CharField(label=_('Page Content'), widget=forms.Textarea(attrs={'rows': 30}))
    mimetype = forms.CharField(label=_('Mime Type'), initial='text/html')

    render = forms.ChoiceField(widget=forms.RadioSelect, choices=RENDER_CHOICES, initial='markdown',
                               label=_('Render Mode'))

    template = forms.ChoiceField(widget=forms.RadioSelect, choices=TEMPLATE_CHOICES, initial='default',
                                 label=_('Template'))
    sidebar = forms.CharField(label=_('Sidebar Content'), widget=forms.Textarea(attrs={'rows': 20}), required=False)
    sidebar_wrap = forms.BooleanField(label=_("Wrap sidebar block"), initial=True, required=False)
    sidebar_render = forms.ChoiceField(widget=forms.RadioSelect, choices=RENDER_CHOICES, initial='markdown',
                                       label=_('Sidebar Render Mode'))

    comments = forms.BooleanField(label=_("Allow comments"), initial=False, required=False)

from forum.forms.auth import SimpleRegistrationForm
from forum.forms.general import SetPasswordForm


class CreateUserForm(SimpleRegistrationForm, SetPasswordForm):
    validate_email = forms.BooleanField(required=False, label=_('send validation email'))

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['username', 'email', 'validate_email', 'password1', 'password2']
        self.fields['email'].label = _('email address')


    

forum/skins/default/templates/account_settings.html
{% extends "base_content.html" %}
<!-- settings.html -->
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Account functions" %}{% endspaceless %}{% endblock %}
{% block head %}
<style type="text/css" media="screen">
    h4 {font-size:12pt;}
	dt, dd { padding:0 0 0.35em 0; }
	dt { float: left; width: 21ex;  }
	dd { margin-left: 23ex;  }
	
	#settings-options, #settings-intro { padding: 4em 1.5em;}
	#settings-options { min-height: 300px; border-left: 1px solid #333;}
	
	#settings-options h5 { font-weight: bold;}
</style>
{% endblock %}

{% block content %}
<div id="main-bar">
    <h3><strong>{{ request.user.username }} {% trans "Profile" %}</strong></h3>
</div>
<div id="settings-options">
	{% if msg %}
		<p class="error">{{ msg }}</p>
	{% endif %}

	<dl class="list-item">
        <dt>&raquo; <a href="{% url "user_changepw" %}">{% trans "Change password" %}</a></dt>
        <dd>{% trans "Give your  account a new password." %}</dd>
        {% comment %}
        <dt>&raquo; <a href="{% url "user_changeemail" %}">{% trans "Change email " %}</a></dt>
        <dd>{% trans "Add or update the email address associated with your account." %}</dd>

        <dt>&raquo; <a href="{% url "user_changeopenid" %}">{% trans "Change OpenID" %}</a></dt>
        <dd>{% trans "Change openid associated to your account" %}</dd>

        
        <dt>&raquo; <a href="{% url "user_delete" %}">{% trans "Delete account" %}</a></dt>
        <dd>{% trans "Erase your username and all your data from website" %}</dd>
        {% endcomment %}
	</dl>
</div>
{% endblock %}
<!-- end settings.html -->

forum/skins/default/templates/add_case.html
{% extends "base.html" %}
<!-- template add_case.html -->
{% load i18n extra_tags extra_filters %}
{% block title %}{% spaceless %}{% trans "Add case" %}{% endspaceless %}{% endblock %}
{% block forejs %}
        <script type='text/javascript' src='{% media  "/media/js/wmd/showdown.js" %}'></script>
        <script type='text/javascript' src='{% media  "/media/js/wmd/wmd.js" %}'></script>
        <script type='text/javascript' src='{% media  "/media/js/html_sanitizer.js" %}'></script>
        <link rel="stylesheet" type="text/css" href="{% media  "/media/js/wmd/wmd.css" %}" />
        <script type="text/html" id="question-summary-template">
            <div class="answer-summary">
                <a href="%URL%"><div class="answer-votes">%SCORE%</div></a>
                <div class="answer-link">
                    <a class="question-hyperlink" href="%URL%" title="%SUMMARY%">%TITLE%</a>
                </div>
            </div>
        </script>
        <script type="text/javascript">
        $(function(){
            //set current module button style
            $("#nav_publish").attr('className',"on");
            $('#editor').TextAreaResizer();

            //toggle preview of editor
            //todo remove copy-paste
            var display = true;
            var txt = "[{% trans "hide preview" %}]";
            $('#pre-collapse').text(txt);
            $('#pre-collapse').bind('click', function(){
                txt = display ? "[{% trans "show preview" %}]" : "[{% trans "hide preview" %}]";
                display = !display;
                $('#previewer').toggle();
                $('#pre-collapse').text(txt);
            });

            //Tags autocomplete action
            $("#id_tags").autocomplete('{% url "matching_tags" %}', {
                minChars: 1,
                matchContains: true,
                max: 10,
                multiple: true,
                multipleSeparator: " ",
                highlightItem: true,
                scroll: true,
                scrollHeight: 300,

                formatItem: function(row, i, max, value) {
                    return row[1] + " (" + row[2] + ")";
                },

                formatResult: function(row, i, max, value){
                    return row[1];
                }

            });

        });

        function submitClicked(e, f) {
            if(!(browserTester('chrome') || browserTester('safari'))) {
                $("input.submit")[0].disabled=true;
            }
            window.removeEventListener('beforeunload', beforeUnload, true);
            if (f) {
                f.submit();
            }
        }

        function beforeUnload(e) {
            if($("input#id_title")[0].value != "" || $("textarea#editor")[0].value != "" || $("input#id_tags")[0].value != "") {
                return yourWorkWillBeLost(e);
            }
        }
        window.addEventListener('beforeunload', beforeUnload, true);

        var related_questions_url = '{% url "related_questions" %}';
        </script>
        <script src="{% media "/media/js/osqa.ask.js" %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<div id="main-bar" class="headNormal">
    {% trans "Publish " %}
</div>
<div id="main-body" class="ask-body">
    <div id="askform">
        <form id="fmask" action="" method="post" accept-charset="utf-8">
            {% csrf_token %}
            {% if not request.user.is_authenticated %}
            
            {% else %}
                {% if not request.user.email_valid_and_can_ask %}
                    <div class="message">
                        {% blocktrans %}Remember, your case study will not be published until you validate your email.{% endblocktrans %}
                        <a href="{% url "send_validation_email" %}">{% trans "Send me a validation link." %}</a>
                    </div>
                {% endif %}
            {% endif %}
            <div class="form-item">
                <label for="id_title" ><strong>{{ form.title.label_tag }}:</strong></label> <span class="form-error"></span><br/>
                {{ form.title }} {{ form.title.errors }}
                <div class="title-desc">
                    {{ form.title.help_text }}
                </div>
            </div>
            <div id="ask-related-questions"></div>
            <div class="form-item">
                <div id="wmd-button-bar" class="wmd-panel"></div>
                {{ form.text }} {{ form.text.errors }}
                <div class="preview-toggle">
                    <table width="100%">
                        <tr>
                            <td>
                                <span id="pre-collapse" title="{% trans "Toggle the real time Markdown editor preview" %}">{% trans "toggle preview" %}</span>
                            </td>
                            <td style="text-align: right;" id="editor-metrics"></td>
                            
                        </tr>

                    </table>
                </div>
                <div id="previewer" class="wmd-preview"></div>
                <span class="form-error"></span>
            </div>
            <div class="form-item">
                <strong>{{ form.tags.label_tag }}:</strong> {% trans "(required)" %} <span class="form-error"></span><br/>
                {{ form.tags }}  {{ form.tags.errors }}
            </div>
			<p class="title-desc">
				{{ form.tags.help_text }}
			</p>
			
            {% if form.recaptcha %}
            <div class="question-captcha" style="float: left">
            	{{ form.recaptcha.errors }}
            	{{ form.recaptcha }}
            </div>
            <div class="clear"></div>
            {% endif %}
			
            {% if not request.user.is_authenticated %}                                                                        
            <input name="add" type="button" value="{% trans "Login/signup to add case study" %}" class="submit" onclick="submitClicked(event, this.form)"/>
			{% else %}
            <input name="add" type="button" value="{% trans "Add case study" %}" class="submit" onclick="submitClicked(event, this.form)"/>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

{% block sidebar %}

{% endblock %}

{% block endjs %}
{% endblock %}
<!-- end template add_case.html -->

forum/skins/default/templates/badge.html
{% extends "base_content.html" %}
<!-- template badge.html -->
{% load i18n %}
{% load extra_tags %}
{% load user_tags %}
{% load humanize %}
{% block title %}{% spaceless %}{{ badge.name }} - {% trans "Badge" %}{% endspaceless %}{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            $("#nav_badges").attr('className',"on");
        });
         
        </script>
{% endblock %}
{% block content %}
<div id="main-bar" class="headNormal">
	{% trans "Badge" %}
</div>
<div id="main-body" style="width:100%;margin-bottom:20px">
    <p>
        <a href="{{badge.get_absolute_url}}" title="{{ badge.get_type_display }} : {{ badge.description }}" class="medal"><span class="badge{{ badge.type }}">&#9679;</span>&nbsp;{{ badge.name }}</a> {{ badge.description }}
    </p>
    <div>
        {% if badge.awarded_count %}
        <p style="float:left"><span class="count">{{ award_count|intcomma }}</span>
        <strong>{% trans "The users have been awarded with badges:" %}</strong></p>
        {% endif %}
    </div>
    <div id="award-list" style="clear:both;margin-left:20px;line-height:25px;">
        {% for award in awards %}
        <p style="width:220px;float:left">{% user_signature award.user "badges" %}<span class="tag-number"> &#215; {{ award.count|intcomma }}</span></p>
        {% endfor %}
    </div>

</div>
{% endblock %}
<!-- end template badge.html -->

forum/skins/default/templates/base.html
{% extends amp|yesno:"amp_base_content.html,base_content.html" %}

{% block page_center %}

{% block full_width_banner %}{% endblock %}

<div id="wrapper">
    {% block site_width_banner %}{% endblock %}
    
    <div id="room">
        <div id="CALeft">
            {% block content%}
            {% endblock%}

        </div>
        <div id="CARight">
            {% block sidebar%}
            {% endblock%}

        </div>
        <div id="tail" style="clear:both;">
            {% block tail %}
            {% endblock %}
        </div>
    </div>
    <div class="spacer3"></div>
</div>
{% endblock %}

forum/skins/default/templates/close.html
{% extends "base_content.html" %}
<!-- template close.html -->
{% load i18n %}
{% load extra_tags %}
{% load humanize %}
{% block title %}{% spaceless %}{% trans "Close question" %}{% endspaceless %}{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            $('#btBack').bind('click', function(){ history.back(); });
        });
        </script>
{% endblock %}
{% block content %}
<div id="main-bar" class="headNormal">
	{% trans "Close question" %}
</div>
<div id="main-body" style="width:100%;margin-bottom:10px">
    <p>{% trans "Close the question" %}: <a href="{{ question.get_absolute_url }}">
    <strong>{{ question.get_question_title }}</strong></a>
    </p>   
    
    <form id="fmclose" action="{% url "close" question.id %}" method="post" >
        {% csrf_token %}
        <p>
            <strong>{% trans "Reasons" %}:</strong> {{ form.reason }}
        </p>
        <div id="" style="padding-top:20px">
            <input type="submit" value="{% trans "OK to close" %}" class="submit" />
            <input id="btBack" type="button" class="submit" value="{% trans "Cancel" %}"  />
            
        </div>
        
    </form>
</div>
{% endblock %}
<!-- end template close.html -->

forum/skins/default/templates/page.html
{% extends base %}
{% load i18n node_tags general_sidebar_tags %}
{% block title %}{% spaceless %}{{ page.title }}{% endspaceless %}{% endblock %}

{% block content %}
<div class="headNormal">{{ page.title }}</div>
<div class="content">
{{ body }}
</div>
{% if page.extra.comments %}
    {% comments page request.user %}
{% endif %}
{% endblock %}

{% ifequal page.extra.template "sidebar" %}
    {% block sidebar %}
        {% sidebar_upper %}
        {% if page.extra.sidebar %}
            {% if page.extra.sidebar_wrap %}<div class="boxC"><div class="body">{% endif %}
                {{ sidebar }}
            {% if page.extra.sidebar_wrap %}</div></div>{% endif %}
        {% endif %}
        {% sidebar_lower %}
    {% endblock %}
{% endifequal %}